version: '3'

services:
  postgresdb:
    image: postgres
    container_name: gobarber_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gobarber
      - POSTGRES_DB=gobarber
    ports:
      - "5432:5432"

  mongodb:
    image: mongo
    container_name: gobarber_mongo
    ports:
      - "27017:27017"

  redisdb:
    image: redis
    container_name: gobarber_redis
    ports:
      - "6379:6379"
